### ISSUE TITLE
Add support of add_theme_support

### ISSUE THREAD

**Issue by Zippovich2** [Zippovich2/wordpress-config#1]
Allow config `add_theme_support`. Example:

```yaml
# config/support.yaml

support:
   title-tag: default # default mean do not pass any parameters
   custom-logo:
      args: { width: 720, height: 480 }
      # or use callback
      args-callback: ClassName:methodName # or use function name
      # also possibility change hook when to call `add_theme_support`, default `after_setup_theme`
      hook: 'init'
```

**Comment by Zippovich2** [comment]
Better idea:
```yaml
# config/support.yaml

support:
   title-tag: true # true/1 - add support, false/0 remove support
   custom-logo:
      args: { width: 720, height: 480 }
      # or use callback
      args-callback: ClassName:methodName # or use function name
      # also possibility change hook when to call `add_theme_support`, default `after_setup_theme`
      hook: init
```
