### ISSUE TITLE
Bug or wrong behavior when use class method as callback in filters and actions

### ISSUE THREAD

**Issue by Zippovich2** [Zippovich2/wordpress-config#2]
In readme file wrong examples, it's should be double colon(using non static method is deprecated) instead single but double colons cannot be parsed, also there is no any info that we must use full name class(with namespace):

```yaml
filters:
   the_content:
      - { callback: App\Filter\Example::content }
```

I think it's should be any config parameter for providing class names prefix for filters and actions.

```yaml
filters:
   the_content:
      - { callback: Example::content }

class_prefix: App\Filter\
```
