### ISSUE TITLE
Ability config image sizes

### ISSUE THREAD

**Issue by Zippovich2** [Zippovich2/wordpress-config#4]
For example:
```yaml
# config/images.yaml

images:
   sizes:
      size_name:
         width: 150
         height: 150
         crop: true # false by default

      thumbnail_large:
         width: 500
         height: 500

      custom_size:
         width: 220
         height: 100
         crop: ['left', 'top'] # Hard crop left top
```

For each size call `add_image_size()` [function](https://developer.wordpress.org/reference/functions/add_image_size/).
